# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f110b5dcf6fb003548ffb016aa1d73c648c09564aed860aa2031f1e52c0ac23a01b91ea75906e0d67deeb823c409a9c79f14c74d04e54c4ca428106d9f89986f

test:
  secret_key_base: 7decfa891fe1eb578ec1b9faa9e6590ad1d3a58cf2f23a8f407d8675eab8d72a61a94faa29119a59f6003237ad1581ea8eff0440191446c1d520c10b875502ea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
